### ISSUE TITLE
Could not load library libcudnn_cnn_train.so.8

### ISSUE THREAD

**Issue by kazuar** [kazuar/Phi3-Vision-ft#1]
When running the `finetune.sh` script, encountered the following error:
```
Could not load library libcudnn_cnn_train.so.8. Error: /usr/local/cuda/lib64/libcudnn_cnn_train.so.8: undefined symbol: _ZN5cudnn3cnn34layerNormFwd_execute_internal_implERKNS_7backend11VariantPackEP11CUstream_stRNS0_18LayerNormFwdParamsERKNS1_20NormForwardOperationEmb, version libcudnn_cnn_infer.so.8
```

I was able to override it by running `unset LD_LIBRARY_PATH` before running the fine-tune script. 

@2U1 did you encounter this? (there's no `issues` section in your repo so I forked it and added the issue here)

**Comment by 2U1** [comment]
Thanks for letting me know.
I haven't encounterd the following issue. I'll test with some other environments.

**Comment by kazuar** [comment]
Also mentioned here in florence 2 finetune script https://github.com/andimarafioti/florence2-finetuning/issues/2

**Comment by 2U1** [comment]
Thanks, I'll add this at the README.

**Comment by kazuar** [comment]
Thanks!
